[package]
name = "porter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.83"
cidr = "0.2.2"
clap = { version = "4.5.4", features = ["derive", "wrap_help"] }
tokio = { version = "1.37.0", features = ["full"] }
